apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-deployment
  labels:
    app: node-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
        - name: node-web
          image: registry.demo.io:5000/node/web:v3
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-service
spec:
  selector:
    app: node-web
  ports:
    - protocol: TCP
      port: 80         # 서비스 포트 (클러스터 내부에서 접근할 때)
      targetPort: 3000  # 컨테이너 내부 포트
      nodePort: 30080   # 외부에서 접근할 포트 (NodePort)
  type: NodePort

